### ISSUE TITLE
Thumbs render out of place initially, only corrected in componentDidMount

### ISSUE THREAD

**Issue by jesseko** [tajo/react-range#10]
Looks like it's measuring things in the browser using getBoundingClientRect and getComputedStyle, which only work after mounted, but that causes an incorrect initial render.  

I'm working with large complex pages that are server-rendered first, so that initial render may persist for longer than acceptable.

Do you think it could be possible to get initial render to be correct?  I'm wondering if that's achievable by passing some dimensional info in as props rather than just managing via custom CSS and measuring later.  Could be tough given how flexible the rendering is, but wonder if you see a way to make that work.  

Really like this component but don't think we can use it without a workaround for that.

**Comment by tajo** [comment]
Well, you need to somehow measure the exact position of the thumb. Afaik the only option would be to provide `initialXY={}` prop and let the developer to provide the correct initial value but that might be hard when your website is responsive and the range width cannot be absolute.

Afaik, there is no way to determine on the server what the exact dimensions are without rendering the whole page and I assume you don't want to run headless chrome on every request.

If your client JS takes too much time to execute, you could at least improve the UX by not displaying the thumb until `componentDidMount` is called and show some loading status instead. But I would definitely focus to make the page interactive faster.

**Comment by jesseko** [comment]
OK, thanks Tajo.  
I think I'm going to go a different route, but appreciate your time to answer this.
