### ISSUE TITLE
values={[800000,2400000]} needs to be sorted when allowOverlap={false}

### ISSUE THREAD

**Issue by Eriickson** [tajo/react-range#111]
when I try to get the data from the url I get this error: "values={[800000,2400000]} needs to be sorted when allowOverlap={false}"

my url: 
![image](https://user-images.githubusercontent.com/38663299/100547033-8319a800-3219-11eb-9827-bed2dfa37d0d.png)

**Comment by tajo** [comment]
[I don't see it](https://codesandbox.io/s/react-range-forked-y42ss?file=/src/index.js).

**Comment by Eriickson** [comment]
@tajo  Well, in truth I have tried everything, and still I do not see how to solve it, I should add that those parameters come from the url parameters, it can be seen in the image

**Comment by tajo** [comment]
Maybe you are passing strings in instead of numbers?

**Comment by Eriickson** [comment]
sorry for waiting, really yes, continuing with the topic, the problem was that I was sending the url parameters as a library parameter without first converting those arguments to integer
