### ISSUE TITLE
Expose RangeProps

### ISSUE THREAD

**Issue by glennreyes** [tajo/react-range#113]
It would be really helpful if the typings for Range props are exposed. Happy to open a PR.

Thanks for making this!

**Comment by tajo** [comment]
Sounds good

**Comment by ffilipovicc98** [comment]
That would be very helpful if we want to move renderTrack callback definition to another file.

I see these types are defined, but it seems like they are not exported.

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/26379911/172611621-7923b11e-d6cb-43ea-b297-58a5cff6d3c6.png">

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/26379911/172611882-ca27ad89-1d22-4c01-ae25-9e27efb1dca1.png">

**Comment by gilbarbara** [comment]
You can simplify the type:

```tsx
type ThumbProps = Parameters<React.ComponentProps<typeof Range>['renderThumb']>[0];
type TrackProps = Parameters<React.ComponentProps<typeof Range>['renderTrack']>[0];
```
