### ISSUE TITLE
Problem if unload react-range during a drag

### ISSUE THREAD

**Issue by mgpGit** [tajo/react-range#117]
Hey There!

I'm running into an issue when during a drag action the component is unloaded. Basically we call this component wrapped inside another component (similar to a modal) that when a mouseUp event occurs outside this "modal" it closes down.

The problem is if you start dragging the slider and move outside this "modal" and mouseUp the component is unloaded but something is still active causing this error.

**Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.**

I tracked the exception to here.  

`
_this.onEnd = function (e) {

....

            // Here! - It can't setState because the modal was closed. 
            _this.setState({ draggedThumbIndex: -1, draggedTrackPos: [-1, -1] }, function () {
                _this.fireOnFinalChange();
            });
`

Any idea on how I can gracefully close down/clean up this component when it has an active drag happening? 

I am able to pinpoint when the close occurs, but not sure what to call?

Thanks in advance!
Mike

**Comment by mgpGit** [comment]
I think I have a simple workaround for this scenario. 

Set a variable that _isMounted=true in componentDidMount() and _isMounted=false in compentWillUnmount().

Then before setting the state in _this.onEnd() check _isMounted=false, if so don't update state.

Would you be willing to accept a PR for this or would you be willing to make the change?

Thanks!
Mike

**Comment by mgpGit** [comment]
Hey @tajo - I created a PR that failed for this check: https://github.com/tajo/react-range/pull/118

I haven't used Yarn before so I attempted a fix w/ my fingers crossed...

BTW - I made these changes to Range.js in my node_modules and that fix worked properly. I'll see if I can create a repro...

**Comment by mgpGit** [comment]
I created a silly repo of this.  

If you mouse over the range component and then outside of the display portion of the codesandbox the range component is successfully hidden.

Refresh the codesandbox. 

Now - start dragging the the Thumb. Keep the mouse down and drag outside the display portion of the codesandbox. 

Errors are thrown that "Cannot read property 'getBoundingClientRect' of null"

https://codesandbox.io/s/react-range-forked-fi03p

It seems that there are other issues here with not gracefully unloading the component such as this error above. 

Thoughts on how to gracefully close out the component?

**Comment by mgpGit** [comment]
Hey @tajo - Could you possibly take a look at my PR?

https://github.com/tajo/react-range/pull/118

I was able to rework the solution by removing a couple listeners on unMount and ignoring the action onMove if the trackElement was not found. 

The last action on onMove was getting triggered by the throttling in requestAnimationFrame. Theoretically we could cancelAnimationFrame on unMount, but that seemed like extra work to keep track of every request action made here.

If possible, please check out my PR for approval of merge.

Thanks!

**Comment by mgpGit** [comment]
Thanks @tajo !

Do you need to tag the change so that I can get the latest changes in my app via my package.json? Ie. 1.8.4?

Or does that automatically happen once further integration steps occur after the merge?

**Comment by tajo** [comment]
published as `1.8.4`
