### ISSUE TITLE
Marks doesnt work in Safari 12

### ISSUE THREAD

**Issue by amin212121** [tajo/react-range#119]
![image](https://user-images.githubusercontent.com/36712833/103148494-e808e500-4768-11eb-8c93-f38572fe1bef.png)

**Comment by tajo** [comment]
Ah, it seems to be fine in Safari v14.

<img width="1239" alt="Screen Shot 2020-12-29 at 10 33 29 AM" src="https://user-images.githubusercontent.com/1387913/103306002-5fd14c80-49c1-11eb-8411-2bbdd89d621d.png">

Do you see any errors in the console?

Technically, we don't support Safari v12 but if there is an easy fix, I'm happy to review a PR.
