### ISSUE TITLE
Align Thumb of React Range Slider so it doesn't go outside bounding box

### ISSUE THREAD

**Issue by deadcoder0904** [tajo/react-range#122]
I am trying to make a range slider & I want to make the thumb (indigo) not go outside the bounding box border (red).

![align thumb of range slider](https://i.stack.imgur.com/IyXLu.png)

If the thumb is small, then it looks perfect but if the thumb is big, which it is in my case, then it looks out of alignment.

I am using React & Tailwind with the help of [react-range](https://github.com/tajo/react-range) library & the code looks like:

```tsx
import * as React from "react"
import { Range } from "react-range"

export default function App() {
	const [values, setValues] = React.useState([50])

	return (
		<div className="w-full flex justify-center">
			<div className="w-48 border-4 border-red-300">
				<h1 className="text-4xl">Range</h1>
				<label>Slider</label>
				<Range
					step={1}
					min={0}
					max={75}
					values={values}
					onChange={(values) => {
						setValues(values)
					}}
					renderTrack={({ props, children }) => (
						<div
							{...props}
							className="w-full h-3 pr-2 my-4 bg-gray-200 rounded-md"
						>
							{children}
						</div>
					)}
					renderThumb={({ props }) => (
						<div
							{...props}
							className="w-5 h-5 transform translate-x-10 bg-indigo-500 rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
						/>
					)}
				/>
				<span>{values[0]}px</span>
			</div>
		</div>
	)
}
```

I have also made a reproducible demo → https://codesandbox.io/s/react-tailwind-align-range-slider-ghyf0?file=/src/App.tsx

I want the thumb to be in alignment with `Slider` & `0px` otherwise it looks off. Even the native range slider doesn't go outside the bounding box. How can I achieve that effect?

**Comment by deadcoder0904** [comment]
Basically want this effect → https://codepen.io/t7team/pen/abNGeXB

**Comment by deadcoder0904** [comment]
I found in the DOM that when the slider is at `0`, there is a `transform: translate(-10px, -4px)` property which displaces the thumb `-10px` backwards.

Whereas if I make it `transform: translate(0px, -4px)`, it looks just fine.

This is where `translate` gets set:

https://github.com/tajo/react-range/blob/bc209f4d33fa28b48d3c266542c456e7af1f6ae3/src/utils.ts#L139

**Comment by tajo** [comment]
This alignment happens on purpose. The thumb is being aligned to its center - that's why you see `transform: translate(-10px, -4px)` when at 0.

> Basically want this effect → https://codepen.io/t7team/pen/abNGeXB

With this implementation, when you move thumbs on top of each other you will see different values which seems strange. The bigger thumb gets, the bigger this difference is.

Even if he had some alternative mode with left/right alignment, not sure how you would apply these for 3+ thumbs or overlapping thumbs.

You can always add some additional padding around the component?

**Comment by deadcoder0904** [comment]
> With this implementation, when you move thumbs on top of each other you will see different values which seems strange. The bigger thumb gets, the bigger this difference is.

I was just giving an example. I don't want 2 thumbs, just one for my current use-case atleast.

Currently, it looks like:

![range](https://user-images.githubusercontent.com/16436270/105138018-4df34d00-5b1a-11eb-892a-7fb631d3d48d.png)

What I'm doing is adding a little margin `ml-2` (I'm using Tailwind) to the `renderTrack` which makes it look weird.

> You can always add some additional padding around the component?

If I do that by adding `pl-2` to the parent `div` & removing the `ml-2` from above, then I get the same effect as the picture above which again looks a bit weird.

Here's what it looks like at `0` with the same margin `ml-2`:

![range](https://user-images.githubusercontent.com/16436270/105138448-e7bafa00-5b1a-11eb-82aa-1addd40ae407.png)

Isn't there any approach to overcome this?

I sort of tried a hack of translating the thumb `4px` ahead when it's on the extreme left-side & `4px` behind when it's on the extreme right-side but it also looks a bit weird by showing the track 4px & the thumb can't go any further.

I'd love to know any approach if you have one.

PS: This is the best library for Range. I tried finding a similar one where I can style it with classes but haven't found one so far. Let me know if you have any suggestions :)

**Comment by tajo** [comment]
As a workaround, you could add some additional element/background that would match the color of track. So it would visually appear as a single longer track.

I get what you are trying to do. It would require some changes to the library - an alternative mode of measurements. If you are interested into contributing, I'm happy to review / help.

**Comment by deadcoder0904** [comment]
> If you are interested into contributing, I'm happy to review / help.

I would've if I knew what to do lol 😂

**Comment by deadcoder0904** [comment]
So I switched to https://github.com/zillow/react-slider & it worked with a tiny bit of changes (although I like `react-range` API a bit more as it's much cleaner):

```tsx
<ReactSlider
  step={1}
  min={0}
  max={75}
  className="w-full h-3 pr-2 my-4 bg-gray-200 rounded-md cursor-grab"
  thumbClassName="absolute w-5 h-5 cursor-grab bg-indigo-500 rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 -top-2px"
  value={value}
  onChange={(value: any) => {
    setValue(value)
  }}
/>
```

Codesandbox → https://codesandbox.io/s/react-tailwind-align-range-slider-ghyf0?file=/src/App.tsx:1082-1458

![react-slider](https://user-images.githubusercontent.com/16436270/105503455-995d5500-5cec-11eb-8aae-06b428b149a4.png)

**Comment by flaviuse** [comment]
If anyone has that problem seeing this issue, to solve it I have set the width of the track as calc(100%-thumbsize) then added an after and before pseudo element to the track to add the missing part of tracks.
Here is a piece of code if needed:
 ```js
const CustomTrack = styled.div`
    height: 4px;
    width: calc(100% - ${THUMB_SIZE});
    border-radius: 2px;
    align-self: center;
    position: relative;

    &::before {
        content: '';
        display: inherit;
        height: 4px;
        width: 12px;
        border-radius: 2px;
        transform: translateX(-11px);
        background-color: #e6e6e6;
        z-index: -1;
    }

    &::after {
        content: '';
        right: 0;
        position: absolute;
        display: inherit;
        height: 4px;
        width: 12px;
        border-radius: 2px;
        transform: translate(11px, -4px);
        background-color: #e6e6e6;
        z-index: -1;
    }
`;
```

**Comment by ch3rn1k** [comment]
Another simple solution is to add another `div` with position `absolute` as fake background line. Here's my solution:

```javascript
<Range
    step={0.1}
    min={0}
    max={100}
    values={[0]}
    renderTrack={({ props, children }) => (
      <div
        {...props}
        style={{
          ...props.style,
          height: '4px',
          width: 'calc(100% - 16px)',
          margin: '0 8px'
        }}
      >
        <div
          style={{
            position: 'absolute',
            height: 4,
            left: -8,
            right: -8,
            background: '#f6f7f9'
          }}
        />
        {children}
      </div>
    )}
    renderThumb={({ props }) => (
      <div
        {...props}
        style={{
          ...props.style,
          height: '18px',
          width: '18px',
          borderRadius: '50%',
          margin: '0 6px',
          backgroundColor: '#2969E0'
        }}
      />
    )}
  />
```

**Comment by hexagoncircle** [comment]
The pseudo element solution in [this comment](https://github.com/tajo/react-range/issues/122#issuecomment-827390047) worked well for me but I needed to solve for one _and_ two thumb versions. I was able to make this styling more dynamic by inheriting the linear gradient value returned from `getTrackBackground()` in a single pseudo element.

[See sandbox](https://codesandbox.io/s/react-range-forked-55ocg)

I use CSS modules in my version but [these styles](https://codesandbox.io/s/react-range-forked-55ocg?file=/src/TwoThumbs.module.css) should translate to whatever solution works for you. I stripped out some rules below to focus on the styling specific to this issue:

```jsx
// Background linear-gradient set in style attribute on the track element
<div
  className={styles.track}
  style={{
    background: getTrackBackground({
      values,
      colors: ["#548BF4", "#ccc"],
      min: MIN,
      max: MAX,
      rtl
    })
  }}
>
  {children}
 </div>
```

```css
/* Store thumb size in CSS variable to reuse for layout positioning */
.wrapper {
  --thumb-size: 42px;
}

.track {
  position: relative;
  display: flex;
  align-self: center;
  height: 5px;
  margin-left: calc(var(--thumb-size) / 2);
  width: calc(100% - var(--thumb-size));
}

.track::before {
  content: "";
  position: absolute;
  margin-left: calc(var(--thumb-size) / -2);
  height: 100%;
  width: calc(100% + var(--thumb-size));
  border-radius: var(--radius-rounded);

 /* Match linear-gradient value from parent (track) background property */
  background: inherit;
}
```

**Comment by louisbarclay** [comment]
@ch3rn1k's solution worked for me. Thanks a lot!

Really nice package btw.
