### ISSUE TITLE
Need for this.markRefs to reset based on change to this.props.max

### ISSUE THREAD

**Issue by TheHaymaker** [tajo/react-range#124]
Hey there.

First off, I just want thank you for building an awesome range slider project. Provides a ton of value to customize appearance and behavior of a range slider in a way that is normalized across modern browsers - which is exactly what I needed.

**The use case I am building for:**
Build a slider that behaves and acts as a slider, but also as a chronological view of snapshot/time series data.

Because of onChange + onFinalChange, and a linked-list map of known values vs. unknown values, we are able to implement this really effectively, even jumping to the closest known value if an empty timeslot is selected, and having keyboard accessibility jump to the next closest known value depending on the direction the user is navigating on the timeline.

We took advantage of conditional rendering marks on the range as well as within the thumb if thumb rests on a known value. The impact is that we can visualize timeseries data with gaps represented accurately, while also allowing users to easily navigate that data while still only snapping to known time-series data.

**The issue I am experiencing:**
We allow users to select different timeframes (e.g. 10-hours, 24-hours, 36-hours, etc, which changes a timeline component that imposes labels and ticks in the background, and we dynamically update the range with the new max value (e.g. if a user selects 24-hours, we create an array of time values for every single minute in a 24-hour period, and the length of that array becomes our max attribute in the range).

We experienced breaking behavior because the list of refs used to render and offset the marks (this.markRefs) does not reset dynamically. And we also ran into an issue in the renderMark callback. We used "display: none" on marks that didn't match any known values, however, "display: none" broke the markOffset functionality when downgrading to a smaller subset of data/smaller range max.

**What we did to fix this:**
To address the markRefs list updating dynamically, I added a clause in componentDidUpdate to reset the markRefs array based on a new max value. If a new max value was passed, first zero out markRefs, then repopulate it with new refs based on new numOfMarks and then run the calculateOffsets function. This seems to keep markOffsets state and markRef list of refs in sync to support dynamic range size changes in conjunction with using/rendering marks and calculating offsets accordingly, and it doesn't seem to break onResize either.

Secondly, I pass one of my maps into Range directly, and based on the availability to the markOffsets index in that map(simple conditional ternary check), I directly modify/toggle opacity and pointer-events directly on the mark (instead of toggling display styles inside of my custom renderMark props function so I don't need to worry if that function is stale).

These two changes were exactly what we needed for our use case.

My interest here is working together to implement this functionality directly into react-range in a tenable, maintainable way without breaking any existing APIs. Currently, since we needed to modify source code, we peeled Range off into our codebase, but would love to improve this for us all and also outline the use case in your examples due to its general utility.

Please let me know. And thanks again for all of your hard work on this thus far. Definitely helped us solve a huge challenge.

**Comment by tajo** [comment]
Nice. Yea, I've never really tested dynamic changes for these props (min, max, step...). The library would definitely deserve some tests and correct implementation (resets). 

I guess that's what causing your issues? As long as it doesn't break existing APIs (not sure why it should?), I'm happy to review any contributions in that direction.

**Comment by tajo** [comment]
merged https://github.com/tajo/react-range/pull/125
