### ISSUE TITLE
Marks offset?

### ISSUE THREAD

**Issue by jgentes** [tajo/react-range#135]
Thanks for the library!

From what I can tell, the marks are fixed. Meaning, the first one is at the start of the track and the last one is at the end, spaced using the step value.

In my case I want the track to start at 0 and the first mark to be at 1. And the same for the end mark, it may be at 12 while the track ends where 13 would be.

I think this could be accomplished with a starting offset. Another option would be to specify the mark values rather than inferring their location based on the step value.

I know that I can workaround this by manipulating the containing div, to size it differently with margins or other tricks, but I don't want to do that.

Any ideas?

**Comment by tranchinamit** [comment]
I think the author should add optional prop "marks" is an array of custom steps e.g. [1, 5, 19.9, 20, 90, 100]. I facing a case with custom  dynamic steps, not fixed steps
