### ISSUE TITLE
Add or remove thumb after first render?

### ISSUE THREAD

**Issue by luizcieslak** [tajo/react-range#136]
Hi! First of all, since it's my first issue here, just wanna thank you for this lib, it's really amazing.

I have a edge case where a range can have either one or two thumbs. I noticed that when you change the `values` array length after the render, the second thumb is not focusable and does not change its value.

Here's the reproducible in a codesandbox: https://codesandbox.io/s/react-range-dynamic-thumb-num-mrobz?file=/src/index.tsx

Is there a way to fix it? Currentlý I'm using two `<Range />`s and switch between them using a ternary operator.

**Comment by SarahFowler73** [comment]
The issue looks like it's in the definition of the `thumbRefs` It's set on mount in the constructor, but does not update on dynamic addition/subtraction of `props.values`.  https://github.com/tajo/react-range/blob/master/src/Range.tsx#L61

I wonder if adding a check to the `componentDidUpdate` to see if the length of values has changed, and updating the refs would fix it. @tajo any thoughts? I'm happy to PR if you don't see an issue with the approach.

**Comment by tajo** [comment]
Happy to review a PR. There might be some other side-effects when trying to change this component dynamically.
