### ISSUE TITLE
Direction: Down + Draggable Track Inverts Track Drag

### ISSUE THREAD

**Issue by emeeks** [tajo/react-range#139]
If I change the settings of the `two-thumbs-with-draggable-track-and-down-direction` example to `direction={direction.Down}` then dragging the thumbs works fine but dragging the track drags the entire track in the opposite direction.

**Comment by zen85** [comment]
i have the same problem and did not find a solution to this. any news on that?

**Comment by zen85** [comment]
here is the solution to a very similar problem when working with arrow-keys - i guess the solution to this problem could work in the same way?

https://github.com/tajo/react-range/pull/163/commits/59e9d59c9b5f1a84495c24d89ea493487ed236f7

**Comment by tajo** [comment]
repro with https://stackblitz.com/edit/react-range-edit?file=src%2FApp.tsx?
