### ISSUE TITLE
Draggable Track has Strange Performance with Ranges Less than 1 or with Negative Min

### ISSUE THREAD

**Issue by emeeks** [tajo/react-range#140]
I've found that the vertical draggable track when dragged on a range that has a negative Min value immediately changes the values on the first mousedown so that the max value becomes the old min value and the new max value becomes a negative value the distance of the original min from the original max.

I also cannot get a draggable track to drag at all for a range where the min and max are both below 1.

**Comment by emeeks** [comment]
These might be the same issue as when the range slider with the minimum value is dragged to the point where the range min equals the extent min, it won't respond at all to being dragged (dragging it "away" from the min).

**Comment by tajo** [comment]
repro with https://stackblitz.com/edit/react-range-edit?file=src%2FApp.tsx?
