### ISSUE TITLE
terrible performance in Two thumb labeled for higher value in max prop

### ISSUE THREAD

**Issue by ArianHamdi** [tajo/react-range#145]
if i set max prop for a high quantity such as 10 millions or 100 millions , it takes too much to be rendered about 3-4 seconds or it would be crashed entirely

**Comment by tajo** [comment]
Do you have 10 million steps in your slider? Generally, I doubt it makes sense to have more steps than pixels on your screen (so thousands should be max).

**Comment by ArianHamdi** [comment]
> Do you have 10 million steps in your slider? Generally, I doubt it makes sense to have more steps than pixels on your screen (so thousands should be max).

Okay so the problem was that of the number of the steps not of max value.
therefore I increased the number of steps and that was ok.
Thanks
