### ISSUE TITLE
Marks only for `min` and `max`

### ISSUE THREAD

**Issue by MrChe** [tajo/react-range#146]
Can we make marks only for `min` and `max`?

**Comment by MrChe** [comment]
![image](https://user-images.githubusercontent.com/9495532/121060065-d3765180-c7ca-11eb-837e-4e8714cc4460.png)

**Comment by tajo** [comment]
^Solution?

**Comment by MrChe** [comment]
@tajo Yeap)

**Comment by MrChe** [comment]
@tajo but if you add step `0.01` its broken(((, it would be great if you add marks only for min and ma like prop or default

**Comment by tajo** [comment]
> but if you add step 0.01 it's broken

that's because `index * step === max`, right ?
