### ISSUE TITLE
Stop labels from moving off screen

### ISSUE THREAD

**Issue by keyranova** [tajo/react-range#148]
Currently if there are long labels, they remain center aligned when at the min/max positions.

It would make more sense to left/right align them at those points.

current example:
<img width="238" alt="Screen Shot 2021-06-29 at 4 49 41 PM" src="https://user-images.githubusercontent.com/4550817/123865962-86355d80-d8fa-11eb-9d1d-e65240fe7b79.png">

super old angularjs slider example I used to use (they're center aligned until the edges are reached):
<img width="223" alt="Screen Shot 2021-06-29 at 4 51 37 PM" src="https://user-images.githubusercontent.com/4550817/123866036-99482d80-d8fa-11eb-9ba2-3a17c1f5d417.png">

since I'm attempting to implement custom labels, has anyone run into this and have a fix?

**Comment by Rusl10** [comment]
@kurtnovack Have you found any solution?
