### ISSUE TITLE
2 thumbs with draggable track - thumb can be dragged while track being dragged

### ISSUE THREAD

**Issue by yann-combarnous** [tajo/react-range#152]
Steps to reproduce:
- use "2 thumbs with draggable track example"
- on a slow machine, drag fast right and left the track, by moving over thumbs
- thumb will also be dragged (so distance between left and right thumbs will change)

This could be avoided by preventing thumbs from being user-draggable while track is being dragged.

**Comment by anik95** [comment]
Hi @yann-combarnous. Did you find anything on this?

**Comment by tajo** [comment]
repro with https://stackblitz.com/edit/react-range-edit?file=src%2FApp.tsx?
