### ISSUE TITLE
Linear gradient for marks over whole range

### ISSUE THREAD

**Issue by Enlitened** [tajo/react-range#153]
I am trying to create a slider that has a linear gradient that is applied to the whole range. i.e. the first and last few marks appear more transparent than the middle marks.

I have tried changing the z-index on the items rendered in renderTrack and renderMark but the marks always appear on of the track.

Something like this:
`background: 'linear-gradient(to right, transparent, white, transparent'`

Is something like this achievable?

**Comment by tajo** [comment]
more like a generic css question?
