### ISSUE TITLE
Demo not work on Safari and Chrome, iPhone 6, iOs 12.5.5

### ISSUE THREAD

**Issue by vaniljs** [tajo/react-range#160]
Does this plugin not work in mobile versions?
White display

![Google Chrome](https://i.ibb.co/r7c3Bdg/2021-11-24-16-32-47.png)
![Safari](https://i.ibb.co/LYkwtqZ/2021-11-24-16-32-27.png)

**Comment by tajo** [comment]
iOS 12 is pretty old, probably some newer API getting broken on this older version of Safari
