### ISSUE TITLE
Stop thumb from overflowing track

### ISSUE THREAD

**Issue by FrancoTanzarella** [tajo/react-range#164]
I would like to constrain the thumb from overflowing the track left and right edge. Currently it will scroll half it's own width past each edge. Is there a way to limit it and keep it inside the track?

Here is an example of what I have currently.
https://codesandbox.io/s/xenodochial-babycat-vmhhl?file=/src/App.js

**Comment by shivamragnar** [comment]
Hey @FrancoTanzarella were you able to get this ?

**Comment by FrancoTanzarella** [comment]
No I ended up not using this package and used my own implementation which wasn't great but it did what I needed it to do.

**Comment by gonzalezi2** [comment]
I had the same issue but I resolved it by using a container div that has padding on it and then used the container to have a background instead of the track element.

Example: 

```jsx
renderTrack={({ props: trackProps, children }) => (
	<div style="padding: 0 6px; background-color: blue">
		<Track  {...trackProps}>{children}</Track>
	</div>
)}
```
