### ISSUE TITLE
Crashes when max size is set to over 10million and step size is 1.

### ISSUE THREAD

**Issue by dilanustek** [tajo/react-range#170]
In the [codesandbox link](https://codesandbox.io/s/rlp1j1183n?file=/src/index.js) that is provided, if you change the MAX to a number over 10million (sometimes 100million), the page crashes. It seems like there might be an array generated with this size since the step size is small here. Given that it takes up too much space, we get a crash. 
<img width="1779" alt="Screen Shot 2022-04-07 at 1 29 46 PM" src="https://user-images.githubusercontent.com/65357508/162290579-3304814d-4cdc-42db-a0e4-637937388535.png">

Is it possible to fix this issue?

**Comment by tajo** [comment]
What's the point trying to render a slider with 100 million steps?
