### ISSUE TITLE
No touchStart removal on unmount

### ISSUE THREAD

**Issue by HYannick** [tajo/react-range#18]
I noticed that on unmount, there is a duplicate here.

https://github.com/tajo/react-range/blob/9b753cb05752b9b69f557d1a137782bcbd586fae/src/Range.tsx#L69

Maybe you ment to remove the `touchStart` event ?

As a fact when we unmount the component on mobile the event remain here with no refs and raise the warning:

`No thumbs found in the track container. Did you forget to pass & spread the `props` param in renderTrack?`

**Comment by tajo** [comment]
Yep. Would you mind to open a PR?
