### ISSUE TITLE
Slider jumps back to the start position in iOS Safari

### ISSUE THREAD

**Issue by shivamragnar** [tajo/react-range#180]
Hey @tajo , Thanks for this amazing library. I think I am getting a issue which other users might also have.
While using the slider in iOS Safari, the slider jumps back to the start position where we started the dragging from. It does not happen everytime to me but yeah it's pretty visible.
What i found out was, the `onChange` event is fired with the wrong value, after we let off the thumb. This is extra onChange that is fired.
I am pretty sure it must be iOS or safari causing it, but I hope if we can workaround this. 
There is a similar issue I found out https://github.com/mui/material-ui/issues/31869.
Here is what I am using
```js
<ImageSlider
    min={3}
    max={100}
    step={0.1}
    values={[value]}
    onChange={handleOnChange}
    onFinalChange={handleFinalChange}
    renderTrack={/* React Node */}
    renderThumb={/* React Node */}
 </>
```
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43090968/189419832-4b1d370d-e14d-4b62-b8ce-d6bb76855568.gif)

**Comment by ardashevdanil** [comment]
Try this, works fine for me
```
<Range
  renderThumb={({ props }) => <Thumb {...props} onTouchEnd={(e) => e.preventDefault()} />}
/>
```

**Comment by luizcieslak** [comment]
@shivamragnar have you found a solution for this?
