### ISSUE TITLE
Would like the ability to focus thumb when clicked

### ISSUE THREAD

**Issue by tvst** [tajo/react-range#21]
What I can do today:
1) Tab tab tab until I reach the thumb
2) Use left/right arrows
...but step (1) is not a great user experience.

What I'd like to do:
1) Click on thumb
2) Use left/right arrows to move it

_or_
1) Drag thumb
2) Use left/right arrows to nudge it to the correct place with more precision

Would it be possible to focus the thumb when clicked?

**Comment by tajo** [comment]
Yea, that makes sense. Do you want to try implementing it?

**Comment by kantuni** [comment]
Hi @tajo,
My name is Henrikh. I work with Thiago (@tvst). 
I've implemented the above mentioned behavior using refs, and can send out a PR if you like.

**Comment by tajo** [comment]
@kantuni Yes please!

**Comment by kantuni** [comment]
> @kantuni Yes please! (Ideally, this should be a built-in functionality, right?)

Yup!
