### ISSUE TITLE
Add support for optional marks (a styled element at each step)

### ISSUE THREAD

**Issue by luisrudge** [tajo/react-range#35]
is there a way to style steps? if not, would you accept a PR to do that?

**Comment by tajo** [comment]
Could you describe it more?

**Comment by luisrudge** [comment]
When I use the `step` prop, I'd like to be able to customize how the step looks like (probably with a `renderStep` method to keep the api consistent.

Example from [material-ui](https://material-ui.com/components/slider/):

![custom steps](https://user-images.githubusercontent.com/941075/64745558-b7069180-d4de-11e9-896f-a24d93c5e33b.gif)

What I actually want to achieve:
![image](https://user-images.githubusercontent.com/941075/64745612-f3d28880-d4de-11e9-9416-74e692882fa3.png)

**Comment by tajo** [comment]
> @tajo but I assume the lib already knows where the steps are, that's how you can 'stick' the thumb to the step correct position. Consumers of the library would have to add code to calculate where the steps should be based on width, size etc..

Yea, the `renderTrack` could pass the positions through a prop. Do you want to give it a try?

**Comment by luisrudge** [comment]
That's a nice idea! I'll give it a shot during the weekend. Thanks for the tip

**Comment by hungle1220** [comment]
> > @tajo but I assume the lib already knows where the steps are, that's how you can 'stick' the thumb to the step correct position. Consumers of the library would have to add code to calculate where the steps should be based on width, size etc..
> 
> Yea, the `renderTrack` could pass the positions through a prop. And there could be some additional `getTrackBackgroundStep` utility function using those steps to generate that background.
> 
> Do you want to give it a try?

@luisrudge what about result bro :D

**Comment by giacomoalonzi** [comment]
it was implemented? I'm trying to use this library to achieve the same result. 
Thanks

**Comment by tajo** [comment]
> this feature has been implemented

It's been not.

**Comment by jameschetwood** [comment]
You can also do this by setting one of the colors in getTrackBackground to "transparent", and by having the linear gradient in a containing div.

**Comment by ianninirojas** [comment]
Hi, was anyone able to style the step break?

**Comment by tajo** [comment]
I'm working on this now.
