### ISSUE TITLE
Allow click to change with two thumbs

### ISSUE THREAD

**Issue by vitalybaev** [tajo/react-range#37]
It will be a nice enhancement to have the ability to change values with two thumbs.
I can make this done a bit later. What do you think?

I think it should be work this way:
1. If click between thumbs - move the closest thumb to the mouse point
2. If click before the first thumb - move it, else if click after the last thumb - move it. Of course, we should respect rtl.

**Comment by tajo** [comment]
Sounds good. Could we generalize it for any number of thumbs?

**Comment by vitalybaev** [comment]
Sure, the first rule works on a click between any thumbs.

**Comment by felix-kaestner** [comment]
@vitalybaev can you confirm that this Issue was resolved by #95 and is working as expected in the latest release (v1.8.0)?
