### ISSUE TITLE
IE 11 Merging labels layout not working

### ISSUE THREAD

**Issue by AndorLundgren** [tajo/react-range#40]
Hi, just observed that in IE 11 the Merging labels example is not correct.
The label is offset right and no labels are merging.

![image](https://user-images.githubusercontent.com/13776860/65943842-b9e70900-e430-11e9-8b04-6fc0d985adcf.png)

Is it a easy fix to make IE 11 work?

**Comment by AndorLundgren** [comment]
Not sure if this is a problem for everyone but I get js errors in IE11 and edge because of missing polyfills.

With this in my index.js create-react-app adds polyfill for react
```
// This must be the first line in src/index.js
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
```
with this in my page will polyfill those js errors I get
```
import 'mdn-polyfills/String.prototype.repeat'
import 'mdn-polyfills/Node.prototype.append'
import 'mdn-polyfills/Node.prototype.remove'
```

The CSS I have not found any fixes for.
I belive it is a IE11 bug where absolute positioned item inside flex item are calculated wrong.
Looks good in Edge (chrashes because of missing polyfill), FF and Chrome.

**Comment by tajo** [comment]
MSIE11 will not be supported anymore.
