### ISSUE TITLE
Feature request: Custom layout of thumbs

### ISSUE THREAD

**Issue by AndorLundgren** [tajo/react-range#41]
I love the useThumbOverlap feature.

Is it possible to to support a thumb render function?
In most of my cases I would like to change the thumb to use, prefix, suffix or thousand seperator.

**Comment by tajo** [comment]
Not sure if I follow, there is already a `renderThumb` function? Can you provide a code example with the desired API?

**Comment by AndorLundgren** [comment]
My bad, explained poorly.

I have based my code on example with useThumbOverlap function.
If I alter the thumb value in the ThumbLabel to be larger than the just the value:
value --> value km/s
The useThumbOverlap will correctly calculate the overlap first time but then when i move it one more tick it will not be correctly rendered (and seperates the thumbs).

My code:
`
const ThumbLabel = ({  rangeRef,  values,  index,  thumbFunction})=> {

  const [labelValue, style] = useThumbOverlap(rangeRef, values, index);

  return (
    <div data-label={index} style={{display: 'block', ...(style) }}>
      {thumbFunction(labelValue)}
    </div>)
}
`

It is because when two thumbs has been merged it will calculate the width of the thumbs by setting the value to innerHtml of not based on the value of the thumb but of value.toFixed(1).

( useThumbOverlap-->const overlaps = getOverlaps(index, offsets, thumbs, values, separator);
--> getThumbWidth: elClone.innerHTML = value.toFixed(1);)
![image](https://user-images.githubusercontent.com/13776860/66157128-6688dc80-e623-11e9-844b-d25157f9cc02.png)
![image](https://user-images.githubusercontent.com/13776860/66157170-7c969d00-e623-11e9-9482-b8b710dcaecf.png)
![image](https://user-images.githubusercontent.com/13776860/66157194-8b7d4f80-e623-11e9-805d-d0840c859e2c.png)

**Comment by robinator8** [comment]
It may also be useful to be able use a string array as an input to useThumbOverlap for values. For my use case I would a playtime (ie 3:25) and a percentage (ie 45%). So instead of 'values' being a number array I think it should be a string array so the user can pass in preformatted values.
