### ISSUE TITLE
translateThumbs on container resize

### ISSUE THREAD

**Issue by readeral** [tajo/react-range#45]
Hi Tajo,

Cool library!

I'm trying to use react-range as one part of a project to replicate the Chrome audio player, which involves two range inputs (one for elapsed time, one for volume) which grow and shrink depending on which element the mouse hovers over.

Having rendered a <Range> component, when resizing the wrapping container the thumb position adjusts down proportionally to the width of the <Range> - but I can't work out how to invoke the inverse behaviour.

Any tips on how to solve this implementation issue?

**Comment by tajo** [comment]
> but I can't work out how to invoke the inverse behaviour

What inverse behavior? Can you provide an example (CodeSandbox).

**Comment by readeral** [comment]
Now that you ask for it, I'm having trouble replicating it! I can cause the issue while changing the width on the wrapping container of the basic range example here https://react-range.netlify.com/?path=/story/range--basic but the thumb positions correctly in my codesandbox. It might be something to do with your example (and my code) using flex - I'll keep trying to reproduce in a simple form, and if I can't, I'll just copy my whole project into a codesandbox :/

**Comment by readeral** [comment]
@tajo Here's a full replication of that part of my project - it's not how I use it in practice, but the behaviour is the same. https://codesandbox.io/s/icy-water-z2qgu

Removing the overflow property on the wrapping container shows where the thumb ends up after the container resize.
Removing the transition property on the wrapping container resolves the problem.

**Comment by readeral** [comment]
Ahhhh so the reason the transition is a problem is because getComputedStyle for getMargin is invoked immediately, but the transition (in my example) takes .2s to run. This means the value for the location of the thumb always represents the place it should've been prior to the animation, rather than the place it needs to be now.

I'm not sure what the solution is if desiring transitions for width

**Comment by tajo** [comment]
You just need to make the range component re-render when your animation is finished. Probably just call `setState` in the parent and pass it as a random prop into  `Range`.

Or you can use ref to call `this.onWindowResize()`. 

this pattern: https://codesandbox.io/embed/kw5mn93wmr

**Comment by readeral** [comment]
Yeah so I was trying to do that (calling onWindowResize) using refs (using hooks and a function component parent) but it didn't want to work for me. I'll have another go.

**Comment by readeral** [comment]
Maybe the difference was finding 'ontransitionend' and using that instead of another callback with a timeout.

**Comment by tajo** [comment]
I didn't know there's the `transitionend` event. That's sweet. Thanks for digging into this!
