### ISSUE TITLE
Controlling tabIndex of rendered thumb

### ISSUE THREAD

**Issue by readeral** [tajo/react-range#46]
Hey again @tajo - it seems like the only way I can have a tabIndex which is not 0 on the thumb is to disable the element. Would you be open to a prop for setting tabIndex?

Something like:
`tabIndex: disabled ? undefined : customTabIndex ? customTabIndex : 0`

**Comment by tajo** [comment]
You can still pass any tabIndex (or any prop in fact) to each thumb?

**Comment by readeral** [comment]
Ah sorry. I have no idea what I was doing wrong, but it's now passing it through :-/ Sorry for wasting your time!
