### ISSUE TITLE
Default Import Error

### ISSUE THREAD

**Issue by patdrew** [tajo/react-range#51]
Using `import React from 'react'` has led to issues with importing types definitions using ES2015 syntax behavior.
I understand it can be fixed by setting the `esModuleInterop` or `allowSyntheticDefaultImports` to true, but that's not an option for me because of the nature of our type configuration.

This could be fixed by updating the first line of **types.d.ts** file from:
- `import React from 'react';`
to
- `import * as React from 'react';` 
![react-range](https://user-images.githubusercontent.com/14352904/70483922-f40eff80-1a9e-11ea-9a29-ed865ea44c56.PNG)
Thank you!

**Comment by tajo** [comment]
Fixed, thanks!
