### ISSUE TITLE
IE11 Error "Object doesn't support property or method 'sign'"

### ISSUE THREAD

**Issue by cdashrowe** [tajo/react-range#52]
When testing in IE the component will sometimes throw the error

`Object doesn't support property or method 'sign'`

It's pointing to the `normaliseValue` function, that function seems to make use of `Math.sign` based on ternary operation.

https://github.com/tajo/react-range/blob/master/src/utils.ts#L38

IE11 does not support Math.sign

**Comment by tajo** [comment]
Hey, do you want to open a PR with fix?

**Comment by cdashrowe** [comment]
I can do yeah.

In what way would you prefer the fix?

Normally something like this would be polyfilled if required, or can remove Math.sign and implement the logic manually?

**Comment by cdashrowe** [comment]
Still going to look into this, had some family stuff going on.

**Comment by cdashrowe** [comment]
@tajo Started looking at a fix, cloned a fresh repo but getting snapshot failures, differences of 0.16% the screenshots look identical.

Am I okay to regenerate?

**Comment by tajo** [comment]
That’s probably because of font rendering. You would need the same environment to get reliable results. So just ignore it. As long as it passes the CI, it’s fine.
