### ISSUE TITLE
Step and decimals past the tenth place

### ISSUE THREAD

**Issue by rastalamm** [tajo/react-range#53]
Ideally, I would like the slider value to display more than 1 digit after the decimal. 

Setting a `step` of `.05` should allow me to scroll from `50.00 -> 50.05 -> 50.10 -> 50.15 -> 50.2`. Instead there is some rounding going on and I am not able to view/step any decimals path the tenth place. I see `50.0 -> 50.1 -> 50.2`

**Comment by rastalamm** [comment]
After some digging, this is only an issue when the `useThumbOverlap` util is used. That function sets the decimal place to 1

**Comment by tajo** [comment]
Thanks for debugging this. Do you want to open a PR? I am out for next two weeks so my responses might be delayed.
