### ISSUE TITLE
styling is not getting applied intially when the model get opened.

### ISSUE THREAD

**Issue by shekharramola** [tajo/react-range#62]
[sandboxlink]https://codesandbox.io/s/beautiful-jennings-wj80v?fontsize=14&hidenavigation=1&theme=darkl)

in this sandbox, when I click open model, the slider pointer is on below the line, but if I click on it,  it jumps to the right place on the line.
Also is there any way to catch up with the value  on opening of modal window. because if I open the modal, move the slide then the number is getting updated but not the styling.
![image](https://user-images.githubusercontent.com/13901619/72805534-22c0ee00-3c79-11ea-8268-e64034b43778.png)

**Comment by tajo** [comment]
The issue is that your modal component is animated and the range component does some measurements when being mounted or updated. You can disable the animation: https://codesandbox.io/s/red-rain-4lb4h

Or you could force the re-rerender once the modal finishes the opening transition.
