### ISSUE TITLE
Is there a way to get to know when the range component is mounted?

### ISSUE THREAD

**Issue by shekharramola** [tajo/react-range#66]
first time when I am clicking on a react range component , I am getting a warning which says
`Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

I have tried adding a flag _isMounted from my end but the error is still coming..

`{
                     this._isMounted && 
                     <Range
                       values={this.props.distanceValue}
                       step={STEP_DISTANCE}
                       min={MIN_DISTANCE}
                       max={MAX_DISTANCE}
                       onChange={value => this.props.setDistanceState({ value })}
                       renderTrack={({ props, children }) => (
                         <div
                           onMouseDown={props.onMouseDown}
                           onTouchStart={props.onTouchStart}
                           style={{
                             ...props.style,
                             height: "36px",
                             display: "flex",
                             width: "100%"
                           }}
                         >
                           <div
                             ref={props.ref}
                             className="winds-blue-bg"
                             style={{
                               height: "5px",
                               width: "100%",
                               borderRadius: "4px",
                               background: getTrackBackground({
                                 values: this.props.distanceValue,
                                 colors: ["#0078D7", "#ccc"],
                                 min: MIN_DISTANCE,
                                 max: MAX_DISTANCE
                               }),
                               alignSelf: "center"
                             }}
                           >
                             {children}
                           </div>
                         </div>
                       )}
                       renderThumb={({ props, isDragged }) => (
                         <div
                           {...props}
                           style={{
                             ...props.style,
                             height: "20px",
                             width: "30px",
                             borderRadius: "4px",
                             backgroundColor: "#0078D7",
                             display: "flex",
                             justifyContent: "center",
                             alignItems: "center",
                             boxShadow: "0px 2px 6px #AAA"
                           }}
                         >
                           <div
                             style={{
                               position: "absolute",
                               top: "0",
                               color: "#fff",
                               fontWeight: "bold",
                               fontSize: "12px",
                               borderRadius: "4px",
                               backgroundColor: "#0078D7"
                             }}
                           >
                             {this.props.distanceValue}
                           </div>
                           <div
                             style={{
                               height: "16px",
                               width: "5px",
                               backgroundColor: isDragged ? "#0078D7" : "#0078D7"
                             }}
                           />
                         </div>
                       )}
                     />
                   }`

**Comment by tajo** [comment]
I am not sure what you are trying to do. If you think there is a bug, please try to reproduce it with [CodeSandbox](https://codesandbox.io/s/rlp1j1183n).

**Comment by shekharramola** [comment]
Actually, I am calling an API on click of slider, and to update the value in the slider, I am not using setSate but redux. can they be related?

**Comment by tajo** [comment]
Sorry, can't help you without a specific example.
