### ISSUE TITLE
Delay on thumb positioning

### ISSUE THREAD

**Issue by Vanals** [tajo/react-range#67]
Hi,

When using React Range on certain occasions, such as when testing the component with Applitools,  or exposing the component through an MDX file, is it possible see the moment when the translate CSS property gets applied to the THUMB and see it moving in the correct position. So we end up having a sort of 'animation' where the initial position of the thumb is the wrong one.

Of course, this is not an ideal behavior we would like to show to the user.  I wonder if there is any fix you could do for it.

Thanks

**Comment by tajo** [comment]
Yea, this is a glitch when doing SSR. The component needs to do some measurements after being mounted to correctly calculate the thumb positions so it's not possible to serve the correct position right away from the server.

As a workaround, you could not render thumbs during the SSR so the initial load would display only the empty track. That might be less noticeable.

Anyway, open to suggestions on this issue.

**Comment by Vanals** [comment]
Make sense, thank you tajo.

**Comment by novyQ** [comment]
We are having similar issue with the initial position of the thumb, which is automatically corrected after resizing the window or click on the thumb. We are not using SSR though...

**Comment by tajo** [comment]
We could probably hide the thumbs until the initial measurement is done.
