### ISSUE TITLE
Nested divs in renderTrack translates track instead of thumb

### ISSUE THREAD

**Issue by safinn** [tajo/react-range#7]
Having 2 divs nested in the render track prop causes the nested div to be translated instead of the thumb as the function `this.getThumbs ` gets the children of the outermost div which is still part of the track and not the thumb.

**Comment by tajo** [comment]
https://github.com/tajo/react-range/blob/master/examples/Basic.tsx#L39

You need to pass the `props.ref` to the innermost div (aka a direct parent of thumbs). Does it help?

**Comment by safinn** [comment]
That indeed does help. Thank you.
