### ISSUE TITLE
Initial position of thumbs is incorrect

### ISSUE THREAD

**Issue by novyQ** [tajo/react-range#70]
The issue happens when the component, a time-picker first renders:
![Screenshot 2020-03-05 at 13 52 49](https://user-images.githubusercontent.com/19396938/75988040-e1af3100-5ee8-11ea-92b4-174f98ab9fd9.png)

Upon inspect, styles of the thumb appears to be:
![Screenshot 2020-03-05 at 13 58 30](https://user-images.githubusercontent.com/19396938/75988491-95b0bc00-5ee9-11ea-80da-14cb8f859138.png)

However, once the page is resized or once the thumb is clicked or dragged, the position will be corrected by itself. 
![Screenshot 2020-03-05 at 14 01 04](https://user-images.githubusercontent.com/19396938/75988648-cf81c280-5ee9-11ea-82d3-0cd29a067dd2.png)

Any idea what might cause the issue? Thanks!

**Comment by tajo** [comment]
Yes, duplicate to https://github.com/tajo/react-range/issues/67

Please use it for more discussion. Closing this issue.
