### ISSUE TITLE
getTrackBackground() not being triggered when there are two tracks

### ISSUE THREAD

**Issue by Xin00163** [tajo/react-range#71]
In our StyledTrack component, we used getTrackBackground() and passed the background color as a prop:
```
      <StyledTrack
        {...trackProps}
        values={trackPositionArr}
        isDragged={isDragged}
        $stylePreset={trackPresets.$sliderTrackStylePreset}
        $trackSize="sizing020"
        $thumbSize="sizing040"
        style={{
          background: getTrackBackground({
            values,
            colors,
            min: 0,
            max: duration,
          }),
        }}
        data-testid="audio-slider-track"
      >
        {trackChildren}
      </StyledTrack>
```
This works perfectly when there is only one track playing. However, when playing two tracks at the same time, getTrackBackground() in the second track didn't render the colour. Could you please advise how we could fix this?

Those two components are on the same page in Storybook:
<img width="1140" alt="Screenshot 2020-03-13 at 10 16 24" src="https://user-images.githubusercontent.com/12214841/76613905-f1e19480-6516-11ea-9809-dcfa081ba6e1.png">
<img width="1139" alt="Screenshot 2020-03-13 at 10 16 32" src="https://user-images.githubusercontent.com/12214841/76613910-f4dc8500-6516-11ea-9127-8c017297cdcb.png">
<img width="1289" alt="Screenshot 2020-03-12 at 09 59 06" src="https://user-images.githubusercontent.com/12214841/76614340-c9a66580-6517-11ea-8891-59cb7eacc071.png">

**Comment by tajo** [comment]
Can't really tell from the description. Could you please try to reproduce it by editing https://codesandbox.io/s/rlp1j1183n? Thanks

**Comment by Xin00163** [comment]
Hi Tajo, I think this is an issue on our end. Will close it. Thank you.
