### ISSUE TITLE
Round step values to nearest value without depending on current state

### ISSUE THREAD

**Issue by woutervh-** [tajo/react-range#87]
I'm not sure whether to call this a suggestion/feature request/UX discussion, so here goes:

Imagine I have a range slider with `min=1`, `max=4`, and `step=1`.
Currently, when I move the slider, the value will change when I reach the next step value.
I would normally expect range sliders value to change to the nearest rounded step value.

This is my expectation from using Windows/Chrome/mouse, maybe on other OS/browser/pointer device combinations this behaves differently?

To clarify:

If I have currently selected 1 and I'm moving the slider from 1 to 4 (to the right):
```
|----|----|----|
1111122222333334
--- mouse position and value of the slider --->
```

If I have currently selected 4 and I'm moving the slider from 4 to 1 (to the left):
```
|----|----|----|
1222223333344444
<--- mouse position and value of the slider ---
```

What I would expect to happen (independent of the current slider value):
```
|----|----|----|
1112222233333444
```

What are your thoughts? Should this be the default behavior? Can there be an option (`prop`) to activate this behavior?

**Comment by tajo** [comment]
Yes, this would a nice improvement. It's also in line with the native input range.
