### ISSUE TITLE
Doesn't work in IE11 -- use of unsupported array methods

### ISSUE THREAD

**Issue by jesseko** [tajo/react-range#9]
The docs state that it should work in IE11 but it doesn't currently because it uses these unsupported methods:
Array.from
Array​.find​Index
Math.sign

Would you be willing to swap those out, replace them with things that do work in IE11?

Looks like it should work other than those!

Thanks,
Jesse

Context:

Array.from
```
_this.getThumbs = function () {
            if (_this.trackRef && _this.trackRef.current) {
                return Array.from(_this.trackRef.current.children);
            }
            console.warn('No thumbs found in the track container. Did you forget to pass & spread the `props` param in renderTrack?');
            return [];
};
```

Array.findIndex
```
        _this.getTargetIndex = function (e) {
            return _this.getThumbs().findIndex(function (child) { return child === e.target || child.contains(e.currentTarget); });
        };
```

Math.sign -- in utils.js
```
    var res = Math.abs(remainder / BIG_NUM) < step / 2
        ? rounded
        : rounded + step * Math.sign(value);
```

**Comment by tajo** [comment]
Yea! Would you mind to open a PR?

**Comment by jesseko** [comment]
I'll take a crack at it!  Thanks

**Comment by jesseko** [comment]
I'm bailing on this because of https://github.com/tajo/react-range/issues/10, sorry, need to find an alternate solution for our site.

But! 
Here'a a simple replacement I wrote for Array.findIndex that will probably handle that one.  You could even take out the first `if` if your args are always guaranteed.

```function ArrayFindIndex(array, func) {
  if (array && array.length && func) {
    for (let i=0; i < array.length; i++) {
      if (func(array[i], i, array)) {
        return i;
      }
    }
  }
  return -1;
}```

and
Math.sign is easy -- via https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sign
```
function sign(x) {
    return ((x > 0) - (x < 0)) || +x;
}
```

**Comment by tajo** [comment]
> The docs state that it should work in IE11 but it doesn't currently because it uses these unsupported methods.

Anyway, I just tested in IE11 (Win 10) and it seems to be working. It should be transpiled to ES5.
