### ISSUE TITLE
Slider track background issue with multiple values and allow overlaping

### ISSUE THREAD

**Issue by piotrrussw** [tajo/react-range#90]
Hi,

I am trying to get slider with 2 thumbs and with allow overlaping option. 
Unfortunately, `getTrackBackground ` function doesn't seem to be working correctly. As i overlap the background of the track is not filled with the middle color which i provide

I created a [demo](https://codesandbox.io/s/vigorous-fermi-7xbsp)
It looks like a bug for me or maybe there is another way to workaround that issue.

**Comment by tajo** [comment]
I think this use-case was just not considered. Should be fixable by re-sorting thumbs before passing them into getTrackBackground or something around that line.

**Comment by piotrrussw** [comment]
Ok, I will provide PR tomorrow

**Comment by piotrrussw** [comment]
Ok, I will try to resolve this tomorrow

**Comment by piotrrussw** [comment]
Yeah, your solution works perfect.
For those who will encounter it later here is second [demo](https://codesandbox.io/s/tender-fire-swxds)
