### ISSUE TITLE
Touch inputs only control first thumb (critical)

### ISSUE THREAD

**Issue by totalolage** [tajo/react-range#97]
This bug prevents use of multi-thumb inputs on mobile.
When the input is a touch event, only the first thumb is consistently controllable. Tapping on the second (rightmost) thumb still controls the first thumb.
Tested on: Android Firefox, Android Chrome, Android Opera, Android Vivaldi
Sandbox: https://mvdm0.csb.app

**Comment by nevolgograd** [comment]
Why this issue is closed!? 
I'm facing the same now, how can i fix it?

**Comment by totalolage** [comment]
Until the fix is published, I have a fork with my fix: https://www.npmjs.com/package/@totalolage/react-range
Once the change goes live switch to the proper package.

**Comment by nevolgograd** [comment]
@totalolage thanks bro, really appreciate it!

**Comment by tajo** [comment]
This PR https://github.com/tajo/react-range/pull/98 was merged and published. It didn't fix it? 

I tested it only on iOS, is this Android specific?

**Comment by tajo** [comment]
Oh, messed up publish. `v1.8.2` should have the fix.
